version: 0.1.{build}

image: Visual Studio 2019
platform: Any CPU

configuration: Debug

before_build:
  - nuget restore PDBSharp.sln

# If you want more build spew, change the verbosity below
build:
  project: PDBSharp.sln
  verbosity: minimal

environment:
  artifacts_dir: bin

test_script:
  - cmd: nunit3-console.exe ./PDBSharp.Tests/bin/%CONFIGURATION%/net472/PDBSharp.Tests.dll --result=myresults.xml;format=AppVeyor
